index:
   path: /
   controller: App\Controller\BasicController::index

app_login:
   path: /login
   controller: App\Controller\SecurityController::login

app_register:
   path: /register
   controller: App\Controller\SecurityController::register 
   
