index:
   path: /
   controller: App\Controller\BasicController::index

app_login:
   path: /login
   controller: App\Controller\SecurityController::login

app_register:
   path: /register
   controller: App\Controller\SecurityController::register 

user_index:
   path: /user/{id}
   controller: App\Controller\UserController::index

user_edit:
   path: /user/{id}/edit
   controller: App\Controller\UserController::edit
   
